# This is a basic workflow to help you get started with Actions

name: Compile LaTeX

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_latex: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
    # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Mengatur repositori Git
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Mengkompile ke PDF dengan latexmk
        uses: dante-ev/latex-action@latest
        with:
          root_file: jadwal.tex
          args: -pdf -interaction=nonstopmode -shell-escape
          
      - name: Membuat rilis
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Versi ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./jadwal.pdf
          asset_name: jadwal.pdf
          asset_content_type: pdf
